In [1]:
import folium as f
import pandas as pd
import seaborn as sns
%matplotlib inline
import numpy as np

In [2]:
pip install folium

Requirement already satisfied: folium in c:\programdata\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from folium) (1.18.5)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from folium) (2.24.0)
Requirement already satisfied: branca>=0.3.0 in c:\programdata\anaconda3\lib\site-packages (from folium) (0.4.1)
Requirement already satisfied: jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (1.25.9)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df1 = pd.read_csv('교차로 및 구간별 교통량 정리- 무수천-신광사거리(수정).csv')
df2 = pd.read_csv('교차로 및 구간별 교통량 정리-마리나-거로사거리(수정).csv')
df3 = pd.read_csv('교차로 및 구간별 교통량 정리- 신시가지입구-중앙여고 교차로.csv')
df4 = pd.read_csv('교차로 및 구간별 교통량 정리- 남문사거리-아라초(수정).csv')

In [4]:
df11 = df1[df1['latitude_x'].notnull()].reset_index()
df11

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4070026600,무수천사가,33.460157,126.446843,-,33.460544,126.447605,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4050005801,-,33.460544,126.447605,광령교,33.460635,126.447795,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,4050005802,광령교,33.460635,126.447795,해군호텔입구,33.460782,126.448079,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4050005803,해군호텔입구,33.460782,126.448079,해안마을,33.463090,126.452479,14098,8217,...,89039,87636,104202,110785,104485,64202,44755,34944,27284,17044
4,4,4050006201,해안마을,33.463090,126.452479,제1해안교,33.463342,126.454106,0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,4050006202,제1해안교,33.463342,126.454106,해안육교,33.465863,126.456384,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6,4050007201,해안육교,33.465863,126.456384,해안병듸,33.469456,126.459953,0,0,...,0,0,0,0,0,0,0,0,0,0
7,7,4050007202,해안병듸,33.469456,126.459953,도근교,33.470483,126.460846,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,4050007203,도근교,33.470483,126.460846,월산마을,33.472819,126.463030,8123,4529,...,73376,76022,88856,100584,90608,57749,34965,26653,19470,11021
9,9,4050008400,월산마을,33.472819,126.463030,월산정수장입구,33.478257,126.468081,59,58,...,294,3,418,586,648,526,263,180,135,74
10,10,4050009000,월산정수장입구,33.478257,126.468081,한라대입구,33.480679,126.472216,6742,3817,...,59454,62171,71395,73003,72416,52065,32333,24372,17561,10352
11,11,4050009600,한라대입구,33.480679,126.472216,-,33.481156,126.472837,0,0,...,0,0,0,0,0,0,0,0,0,0
12,12,4050010000,-,33.481156,126.472837,-,33.481901,126.473756,0,0,...,0,0,0,0,0,0,0,0,0,0
13,13,4050010600,-,33.481901,126.473756,노형새마을금고,33.482819,126.474875,0,0,...,0,0,0,0,0,0,0,0,0,0
14,14,4050011000,노형새마을금고,33.482819,126.474875,-,33.483418,126.475600,0,0,...,0,0,0,0,0,0,0,0,0,0
15,15,4050011200,-,33.483418,126.475600,노형초교앞삼거리,33.483963,126.476259,0,0,...,0,0,0,0,0,0,0,0,0,0
16,16,4050011400,노형초교앞삼거리,33.483963,126.476259,-,33.484642,126.477124,0,0,...,0,0,0,0,0,0,0,0,0,0
17,17,4050012000,-,33.484642,126.477124,-,33.485055,126.477810,0,0,...,0,0,0,0,0,0,0,0,0,0
18,18,4050012200,-,33.485055,126.477810,-,33.485278,126.478223,0,0,...,0,0,0,0,0,0,0,0,0,0
19,19,4050012800,-,33.485278,126.478223,노형오거리,33.486000,126.479550,6058,3467,...,55885,53414,59873,58655,60827,42188,30315,23241,17956,9561
20,20,4050013100,노형오거리,33.486000,126.479550,노형파출소,33.486327,126.480150,0,0,...,0,0,0,0,0,0,0,0,0,0
21,21,4050013600,노형파출소,33.486327,126.480150,건강보험공단,33.487088,126.481498,0,0,...,0,0,0,0,0,0,0,0,0,0
22,22,4050013800,건강보험공단,33.487088,126.481498,-,33.487756,126.482512,0,0,...,0,0,0,0,0,0,0,0,0,0
23,23,4050014400,-,33.487756,126.482512,남녕고사가,33.488395,126.483507,15321,10352,...,60911,60072,64366,65355,61984,53632,42739,37361,30414,20744
24,24,4050015000,남녕고사가,33.488395,126.483507,한라병원사가,33.490078,126.486558,0,0,...,0,0,0,0,0,0,0,0,0,0
25,25,4050015800,한라병원사가,33.490078,126.486558,-,33.490805,126.487861,0,0,...,0,0,0,0,0,0,0,0,0,0
26,26,4050016000,-,33.490805,126.487861,-,33.491513,126.489081,0,0,...,0,0,0,0,0,0,0,0,0,0
27,27,4050016600,-,33.491513,126.489081,삼무공원사가,33.492335,126.490247,9291,5643,...,55315,52936,56881,54568,53042,42953,34317,28429,21684,13628
28,28,4050017200,삼무공원사가,33.492335,126.490247,신광사거리,33.493793,126.492189,15001,10983,...,53938,52341,56943,56071,56514,45798,38619,32537,27093,19524

In [5]:
df21 = df2[df2['latitude_x'].notnull()].reset_index()
df21

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4050134300,마리나사거리,33.493624,126.496769,NaN,33.493566,126.497524,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4050133900,NaN,33.493566,126.497524,세기1차,33.493458,126.500128,4,2,...,8,9,2,5,5,4,5,4,2,2
2,2,4050132700,세기1차,33.493458,126.500128,연미마을,33.493031,126.508188,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4050132100,연미마을,33.493031,126.508188,사평마을,33.492842,126.511255,13534,9532,...,61796,63298,67384,68681,72372,51307,40101,32472,28231,19107
4,4,4050131400,사평마을,33.492842,126.511255,오라대교,33.492567,126.515227,0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,4050130600,오라대교,33.492567,126.515227,오라1동,33.492444,126.516872,16177,11025,...,71761,70911,74707,78944,80950,56342,45024,38968,31967,22830
6,6,4050129300,오라1동,33.492444,126.516872,보건소사거리,33.492272,126.519711,14098,9850,...,62135,59562,60481,64490,65644,48362,38961,34032,26929,18452
7,7,4050128700,보건소사거리,33.492272,126.519711,도노교,33.492223,126.521426,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,4050127600,도노교,33.492223,126.521426,제주지방합동청사삼거리,33.492139,126.528250,12980,8347,...,53306,50948,52246,53783,56008,42365,36703,32631,25289,17780
9,10,4050127700,도남사거리,33.492139,126.528250,-,33.493090,126.531131,0,0,...,0,0,0,0,0,0,0,0,0,0
10,12,4050136300,8호광장,33.494763,126.533654,-,33.495530,126.534789,0,0,...,0,0,0,0,0,0,0,0,0,0
11,13,4050139100,-,33.495530,126.534789,이도2동주민센터,33.496243,126.535822,0,0,...,0,0,0,0,0,0,0,0,0,0
12,14,4050142300,이도2동주민센터,33.496243,126.535822,-,33.496945,126.536884,0,0,...,0,0,0,0,0,0,0,0,0,0
13,15,4050144700,-,33.496945,126.536884,변전소사거리,33.497641,126.537961,14223,9759,...,52778,52372,54596,55295,59067,47923,38424,35326,28748,21009
14,16,4050147700,변전소사거리,33.497641,126.537961,NaN,33.498544,126.539693,0,0,...,0,0,0,0,0,0,0,0,0,0
15,17,4050150800,NaN,33.498544,126.539693,산지2교,33.499427,126.541298,0,0,...,0,0,0,0,0,0,0,0,0,0
16,18,4050152600,산지2교,33.499427,126.541298,제주은행사거리,33.500772,126.543837,12061,7875,...,48963,46373,45382,47391,47688,38213,30812,29060,22920,16444
17,19,4050156500,제주은행사거리,33.500772,126.543837,동광초교,33.502681,126.547462,11524,7494,...,42952,40186,41686,42589,43449,33208,27647,26740,21404,16221
18,20,4050160700,동광초교,33.502681,126.547462,우성아파트사거리,33.504378,126.550611,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df31 = df3[df3['latitude_x'].notnull()].reset_index()
df31

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4.050059e+09,신시가지입구,33.481796,126.494866,정실입구교차로,33.481805,126.496594,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,4.050058e+09,정실입구교차로,33.481805,126.496594,연화사입구,33.481291,126.508627,12762.0,8181.0,...,62390.0,59452.0,66128.0,67450.0,66092.0,51968.0,40870.0,36346.0,27425.0,19052.0
2,2,4.050055e+09,연화사입구,33.481291,126.508627,보건소남측사거리,33.481062,126.515579,7822.0,4632.0,...,55881.0,51986.0,57949.0,59697.0,62796.0,44785.0,32545.0,28838.0,19777.0,12309.0
3,3,4.050055e+09,보건소남측사거리,33.481062,126.515579,연북2교,33.481027,126.516615,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4.050054e+09,연북2교,33.481027,126.516615,연북2교,33.480946,126.518320,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,4.050054e+09,연북2교,33.480946,126.518320,연북2교동측,33.480931,126.518991,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6,4.050054e+09,연북2교동측,33.480931,126.518991,연북3교,33.480682,126.525322,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,7,4.050054e+09,연북3교,33.480682,126.525322,오등동입구,33.481354,126.530093,12581.0,8540.0,...,63163.0,60821.0,62597.0,67445.0,67417.0,51219.0,38659.0,34191.0,26282.0,17056.0
8,8,4.050058e+09,오등동입구,33.481354,126.530093,NaN,33.485485,126.537090,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,9,1.100000e+09,메가박스앞,33.485485,126.537090,구산마을입구,33.485485,126.537090,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,4.050084e+09,구산마을입구,33.485485,126.537090,평강교회,33.486116,126.538045,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,11,4.050092e+09,평강교회,33.486116,126.538045,중앙여고사거리,33.487633,126.540414,6156.0,3576.0,...,40147.0,37687.0,40310.0,42637.0,45555.0,33290.0,24777.0,20921.0,15296.0,9142.0

In [7]:
df41 = df4[df4['latitude_x'].notnull()].reset_index()
df41

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4050027800,남문사거리,33.509468,126.523491,제주시민회관,33.507812,126.524350,NaN,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4050027201,제주시민회관,33.507812,126.524350,칼호텔북측,33.505813,126.525547,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,4050026800,칼호텔북측,33.505813,126.525547,KAL사거리,33.504811,126.526240,NaN,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4050026300,KAL사거리,33.504811,126.526240,광양사거리,33.500730,126.529107,NaN,0,...,0,0,0,0,0,0,0,0,0,0
4,4,4050024500,광양사거리,33.500730,126.529107,제주시민원실,33.499509,126.529930,0.0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,4050023500,제주시민원실,33.499509,126.529930,구간전사거리,33.497725,126.531133,NaN,35667,...,69891,67521,70735,73304,76909,66141,64217,60516,56340,52422
6,6,4050023100,구간전사거리,33.497725,126.531133,-,33.497128,126.531604,0.0,0,...,0,0,0,0,0,0,0,0,0,0
7,7,4050022700,-,33.497128,126.531604,세무서앞삼거리,33.496316,126.532152,0.0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,4050021900,세무서앞삼거리,33.496316,126.532152,-,33.495239,126.533123,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9,9,4050021100,-,33.495239,126.533123,8호광장,33.494763,126.533654,17218.0,13081,...,39090,37207,38406,39096,40942,34395,30364,27582,27582,18857
10,10,4050017300,8호광장,33.494763,126.533654,법원사거리,33.492718,126.535597,0.0,0,...,0,0,0,0,0,0,0,0,0,0
11,11,4050016300,법원사거리,33.492718,126.535597,소방서앞사거리,33.491863,126.536409,23200.0,15522,...,54900,50980,54081,54569,54650,48181,42714,39763,36648,29761
12,12,4050015102,소방서앞사거리,33.491863,126.536409,-,33.490311,126.537910,0.0,0,...,0,0,0,0,0,0,0,0,0,0
13,13,4050015101,-,33.490311,126.537910,중앙여고입구,33.489161,126.539000,0.0,0,...,0,0,0,0,0,0,0,0,0,0
14,14,4050013900,중앙여고입구,33.489161,126.539000,중앙여고사거리,33.487633,126.540414,0.0,0,...,0,0,0,0,0,0,0,0,0,0
15,15,4050012900,중앙여고사거리,33.487633,126.540414,제주여중고입구,33.485489,126.542504,NaN,8558,...,46386,41935,45206,44641,45001,37140,31645,28811,20279,17191
16,16,4050009301,제주여중고입구,33.485489,126.542504,-,33.483550,126.543420,0.0,0,...,0,0,0,0,0,0,0,0,0,0
17,17,4050009302,-,33.483550,126.543420,아라초등학교,33.478001,126.543843,7500.0,4422,...,45364,42351,44262,44592,47134,34148,27879,24642,16314,11409

In [8]:
df_fin = pd.concat([df11,df21,df31,df41],axis=0)
df_fin

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4.070027e+09,무수천사가,33.460157,126.446843,-,33.460544,126.447605,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,4.050006e+09,-,33.460544,126.447605,광령교,33.460635,126.447795,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,4.050006e+09,광령교,33.460635,126.447795,해군호텔입구,33.460782,126.448079,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,4.050006e+09,해군호텔입구,33.460782,126.448079,해안마을,33.463090,126.452479,14098.0,8217.0,...,89039.0,87636.0,104202.0,110785.0,104485.0,64202.0,44755.0,34944.0,27284.0,17044.0
4,4,4.050006e+09,해안마을,33.463090,126.452479,제1해안교,33.463342,126.454106,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,13,4.050015e+09,-,33.490311,126.537910,중앙여고입구,33.489161,126.539000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,14,4.050014e+09,중앙여고입구,33.489161,126.539000,중앙여고사거리,33.487633,126.540414,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,15,4.050013e+09,중앙여고사거리,33.487633,126.540414,제주여중고입구,33.485489,126.542504,NaN,8558.0,...,46386.0,41935.0,45206.0,44641.0,45001.0,37140.0,31645.0,28811.0,20279.0,17191.0
16,16,4.050009e+09,제주여중고입구,33.485489,126.542504,-,33.483550,126.543420,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,17,4.050009e+09,-,33.483550,126.543420,아라초등학교,33.478001,126.543843,7500.0,4422.0,...,45364.0,42351.0,44262.0,44592.0,47134.0,34148.0,27879.0,24642.0,16314.0,11409.0

In [9]:
lines = []
for i in range(len(df_fin)):
    lines.append(df_fin[['latitude_x','longitude_x']].values[i].tolist())
    lines.append(df_fin[['latitude_y','longitude_y']].values[i].tolist())
lines

[[33.460157, 126.44684299999999],
 [33.460544, 126.44760500000001],
 [33.460544, 126.44760500000001],
 [33.460634999999996, 126.447795],
 [33.460634999999996, 126.447795],
 [33.460782, 126.448079],
 [33.460782, 126.448079],
 [33.46309, 126.452479],
 [33.46309, 126.452479],
 [33.463342, 126.45410600000001],
 [33.463342, 126.45410600000001],
 [33.465863, 126.45638400000001],
 [33.465863, 126.45638400000001],
 [33.469456, 126.459953],
 [33.469456, 126.459953],
 [33.470483, 126.46084599999999],
 [33.470483, 126.46084599999999],
 [33.472819, 126.46303],
 [33.472819, 126.46303],
 [33.478257, 126.46808100000001],
 [33.478257, 126.46808100000001],
 [33.480678999999995, 126.47221599999999],
 [33.480678999999995, 126.47221599999999],
 [33.481156, 126.47283700000001],
 [33.481156, 126.47283700000001],
 [33.481901, 126.47375600000001],
 [33.481901, 126.47375600000001],
 [33.482819, 126.474875],
 [33.482819, 126.474875],
 [33.483418, 126.4756],
 [33.483418, 126.4756],
 [33.483963, 126.47625900000001],
 [33.483963, 126.47625900000001],
 [33.484642, 126.477124],
 [33.484642, 126.477124],
 [33.485054999999996, 126.47781],
 [33.485054999999996, 126.47781],
 [33.485278, 126.478223],
 [33.485278, 126.478223],
 [33.486, 126.47955],
 [33.486, 126.47955],
 [33.486327, 126.48015],
 [33.486327, 126.48015],
 [33.487088, 126.481498],
 [33.487088, 126.481498],
 [33.487756, 126.48251200000001],
 [33.487756, 126.48251200000001],
 [33.488395000000004, 126.483507],
 [33.488395000000004, 126.483507],
 [33.490078000000004, 126.486558],
 [33.490078000000004, 126.486558],
 [33.490805, 126.48786100000001],
 [33.490805, 126.48786100000001],
 [33.491513, 126.489081],
 [33.491513, 126.489081],
 [33.492335, 126.490247],
 [33.492335, 126.490247],
 [33.493793, 126.492189],
 [33.493624, 126.496769],
 [33.493565999999994, 126.497524],
 [33.493565999999994, 126.497524],
 [33.493458000000004, 126.500128],
 [33.493458000000004, 126.500128],
 [33.493031, 126.50818799999999],
 [33.493031, 126.50818799999999],
 [33.492841999999996, 126.511255],
 [33.492841999999996, 126.511255],
 [33.492567, 126.515227],
 [33.492567, 126.515227],
 [33.492444, 126.51687199999999],
 [33.492444, 126.51687199999999],
 [33.492272, 126.51971100000002],
 [33.492272, 126.51971100000002],
 [33.492222999999996, 126.521426],
 [33.492222999999996, 126.521426],
 [33.492139, 126.52825],
 [33.492139, 126.52825],
 [33.49309, 126.531131],
 [33.494763, 126.533654],
 [33.49553, 126.53478899999999],
 [33.49553, 126.53478899999999],
 [33.496243, 126.535822],
 [33.496243, 126.535822],
 [33.496945000000004, 126.53688400000001],
 [33.496945000000004, 126.53688400000001],
 [33.497640999999994, 126.53796100000001],
 [33.497640999999994, 126.53796100000001],
 [33.498544, 126.539693],
 [33.498544, 126.539693],
 [33.499427000000004, 126.541298],
 [33.499427000000004, 126.541298],
 [33.500772, 126.54383700000001],
 [33.500772, 126.54383700000001],
 [33.502681, 126.54746200000001],
 [33.502681, 126.54746200000001],
 [33.504378, 126.550611],
 [33.481796, 126.49486599999999],
 [33.481805, 126.49659399999999],
 [33.481805, 126.49659399999999],
 [33.481291, 126.508627],
 [33.481291, 126.508627],
 [33.481062, 126.515579],
 [33.481062, 126.515579],
 [33.481027000000005, 126.51661499999999],
 [33.481027000000005, 126.51661499999999],
 [33.480946, 126.51831999999999],
 [33.480946, 126.51831999999999],
 [33.480931, 126.51899099999999],
 [33.480931, 126.51899099999999],
 [33.480682, 126.525322],
 [33.480682, 126.525322],
 [33.481353999999996, 126.530093],
 [33.481353999999996, 126.530093],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.486115999999996, 126.538045],
 [33.486115999999996, 126.538045],
 [33.487633, 126.54041399999998],
 [33.509468, 126.52349099999999],
 [33.507812, 126.52435],
 [33.507812, 126.52435],
 [33.505813, 126.525547],
 [33.505813, 126.525547],
 [33.504811, 126.52623999999999],
 [33.504811, 126.52623999999999],
 [33.50073, 126.52910700000001],
 [33.50073, 126.52910700000001],
 [33.499509, 126.52993000000001],
 [33.499509, 126.52993000000001],
 [33.497725, 126.53113300000001],
 [33.497725, 126.53113300000001],
 [33.497128000000004, 126.531604],
 [33.497128000000004, 126.531604],
 [33.496316, 126.532152],
 [33.496316, 126.532152],
 [33.495239, 126.533123],
 [33.495239, 126.533123],
 [33.494763, 126.533654],
 [33.494763, 126.533654],
 [33.492717999999996, 126.535597],
 [33.492717999999996, 126.535597],
 [33.491863, 126.536409],
 [33.491863, 126.536409],
 [33.490311, 126.53791000000001],
 [33.490311, 126.53791000000001],
 [33.489160999999996, 126.539],
 [33.489160999999996, 126.539],
 [33.487633, 126.54041399999998],
 [33.487633, 126.54041399999998],
 [33.485489, 126.54250400000001],
 [33.485489, 126.54250400000001],
 [33.48355, 126.54342],
 [33.48355, 126.54342],
 [33.478001, 126.543843]]

In [10]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines,
          tooltip = 'PolyLine').add_to(m)
#m.save('재영.html')

In [11]:
lines1 = []
for i in range(len(df11)):
    lines1.append(df11[['latitude_x','longitude_x']].values[i].tolist())
    lines1.append(df11[['latitude_y','longitude_y']].values[i].tolist())
lines1

[[33.460157, 126.44684299999999],
 [33.460544, 126.44760500000001],
 [33.460544, 126.44760500000001],
 [33.460634999999996, 126.447795],
 [33.460634999999996, 126.447795],
 [33.460782, 126.448079],
 [33.460782, 126.448079],
 [33.46309, 126.452479],
 [33.46309, 126.452479],
 [33.463342, 126.45410600000001],
 [33.463342, 126.45410600000001],
 [33.465863, 126.45638400000001],
 [33.465863, 126.45638400000001],
 [33.469456, 126.459953],
 [33.469456, 126.459953],
 [33.470483, 126.46084599999999],
 [33.470483, 126.46084599999999],
 [33.472819, 126.46303],
 [33.472819, 126.46303],
 [33.478257, 126.46808100000001],
 [33.478257, 126.46808100000001],
 [33.480678999999995, 126.47221599999999],
 [33.480678999999995, 126.47221599999999],
 [33.481156, 126.47283700000001],
 [33.481156, 126.47283700000001],
 [33.481901, 126.47375600000001],
 [33.481901, 126.47375600000001],
 [33.482819, 126.474875],
 [33.482819, 126.474875],
 [33.483418, 126.4756],
 [33.483418, 126.4756],
 [33.483963, 126.47625900000001],
 [33.483963, 126.47625900000001],
 [33.484642, 126.477124],
 [33.484642, 126.477124],
 [33.485054999999996, 126.47781],
 [33.485054999999996, 126.47781],
 [33.485278, 126.478223],
 [33.485278, 126.478223],
 [33.486, 126.47955],
 [33.486, 126.47955],
 [33.486327, 126.48015],
 [33.486327, 126.48015],
 [33.487088, 126.481498],
 [33.487088, 126.481498],
 [33.487756, 126.48251200000001],
 [33.487756, 126.48251200000001],
 [33.488395000000004, 126.483507],
 [33.488395000000004, 126.483507],
 [33.490078000000004, 126.486558],
 [33.490078000000004, 126.486558],
 [33.490805, 126.48786100000001],
 [33.490805, 126.48786100000001],
 [33.491513, 126.489081],
 [33.491513, 126.489081],
 [33.492335, 126.490247],
 [33.492335, 126.490247],
 [33.493793, 126.492189]]

In [12]:
lines2 = []
for i in range(len(df21)):
    lines2.append(df21[['latitude_x','longitude_x']].values[i].tolist())
    lines2.append(df21[['latitude_y','longitude_y']].values[i].tolist())
lines2

[[33.493624, 126.496769],
 [33.493565999999994, 126.497524],
 [33.493565999999994, 126.497524],
 [33.493458000000004, 126.500128],
 [33.493458000000004, 126.500128],
 [33.493031, 126.50818799999999],
 [33.493031, 126.50818799999999],
 [33.492841999999996, 126.511255],
 [33.492841999999996, 126.511255],
 [33.492567, 126.515227],
 [33.492567, 126.515227],
 [33.492444, 126.51687199999999],
 [33.492444, 126.51687199999999],
 [33.492272, 126.51971100000002],
 [33.492272, 126.51971100000002],
 [33.492222999999996, 126.521426],
 [33.492222999999996, 126.521426],
 [33.492139, 126.52825],
 [33.492139, 126.52825],
 [33.49309, 126.531131],
 [33.494763, 126.533654],
 [33.49553, 126.53478899999999],
 [33.49553, 126.53478899999999],
 [33.496243, 126.535822],
 [33.496243, 126.535822],
 [33.496945000000004, 126.53688400000001],
 [33.496945000000004, 126.53688400000001],
 [33.497640999999994, 126.53796100000001],
 [33.497640999999994, 126.53796100000001],
 [33.498544, 126.539693],
 [33.498544, 126.539693],
 [33.499427000000004, 126.541298],
 [33.499427000000004, 126.541298],
 [33.500772, 126.54383700000001],
 [33.500772, 126.54383700000001],
 [33.502681, 126.54746200000001],
 [33.502681, 126.54746200000001],
 [33.504378, 126.550611]]

In [13]:
lines3 = []
for i in range(len(df31)):
    lines3.append(df31[['latitude_x','longitude_x']].values[i].tolist())
    lines3.append(df31[['latitude_y','longitude_y']].values[i].tolist())
lines3

[[33.481796, 126.49486599999999],
 [33.481805, 126.49659399999999],
 [33.481805, 126.49659399999999],
 [33.481291, 126.508627],
 [33.481291, 126.508627],
 [33.481062, 126.515579],
 [33.481062, 126.515579],
 [33.481027000000005, 126.51661499999999],
 [33.481027000000005, 126.51661499999999],
 [33.480946, 126.51831999999999],
 [33.480946, 126.51831999999999],
 [33.480931, 126.51899099999999],
 [33.480931, 126.51899099999999],
 [33.480682, 126.525322],
 [33.480682, 126.525322],
 [33.481353999999996, 126.530093],
 [33.481353999999996, 126.530093],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.486115999999996, 126.538045],
 [33.486115999999996, 126.538045],
 [33.487633, 126.54041399999998]]

In [14]:
lines4 = []
for i in range(len(df41)):
    lines4.append(df41[['latitude_x','longitude_x']].values[i].tolist())
    lines4.append(df41[['latitude_y','longitude_y']].values[i].tolist())
lines4

[[33.509468, 126.52349099999999],
 [33.507812, 126.52435],
 [33.507812, 126.52435],
 [33.505813, 126.525547],
 [33.505813, 126.525547],
 [33.504811, 126.52623999999999],
 [33.504811, 126.52623999999999],
 [33.50073, 126.52910700000001],
 [33.50073, 126.52910700000001],
 [33.499509, 126.52993000000001],
 [33.499509, 126.52993000000001],
 [33.497725, 126.53113300000001],
 [33.497725, 126.53113300000001],
 [33.497128000000004, 126.531604],
 [33.497128000000004, 126.531604],
 [33.496316, 126.532152],
 [33.496316, 126.532152],
 [33.495239, 126.533123],
 [33.495239, 126.533123],
 [33.494763, 126.533654],
 [33.494763, 126.533654],
 [33.492717999999996, 126.535597],
 [33.492717999999996, 126.535597],
 [33.491863, 126.536409],
 [33.491863, 126.536409],
 [33.490311, 126.53791000000001],
 [33.490311, 126.53791000000001],
 [33.489160999999996, 126.539],
 [33.489160999999996, 126.539],
 [33.487633, 126.54041399999998],
 [33.487633, 126.54041399999998],
 [33.485489, 126.54250400000001],
 [33.485489, 126.54250400000001],
 [33.48355, 126.54342],
 [33.48355, 126.54342],
 [33.478001, 126.543843]]

In [15]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines1, color='green',
          tooltip = 'PolyLine').add_to(m)
m.save('재영3.html')

In [16]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines2, color='red',
          tooltip = 'PolyLine').add_to(m)
m.save('재영3.html')

In [17]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines3, color='yellow',
          tooltip = 'PolyLine').add_to(m)
m.save('재영3.html')

In [18]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines4, color='blue',
          tooltip = 'PolyLine').add_to(m)
m.save('재영3.html')

In [19]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines1, color='green',
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines2, color='red',
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines3, color='purple',
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines4, color='blue',
          tooltip = 'PolyLine').add_to(m)
m.save('재영3.html')

In [20]:
lines3_1 = []
lines3_1.append(df31[['latitude_x','longitude_x']].values[0].tolist())
lines3_1.append(df31[['latitude_y','longitude_y']].values[0].tolist())
lines3_1

[[33.481796, 126.49486599999999], [33.481805, 126.49659399999999]]

In [21]:
lines3_2 = []
for i in range(1,11):
    lines3_2.append(df31[['latitude_x','longitude_x']].values[i].tolist())
    lines3_2.append(df31[['latitude_y','longitude_y']].values[i].tolist())
lines3_2

[[33.481805, 126.49659399999999],
 [33.481291, 126.508627],
 [33.481291, 126.508627],
 [33.481062, 126.515579],
 [33.481062, 126.515579],
 [33.481027000000005, 126.51661499999999],
 [33.481027000000005, 126.51661499999999],
 [33.480946, 126.51831999999999],
 [33.480946, 126.51831999999999],
 [33.480931, 126.51899099999999],
 [33.480931, 126.51899099999999],
 [33.480682, 126.525322],
 [33.480682, 126.525322],
 [33.481353999999996, 126.530093],
 [33.481353999999996, 126.530093],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.486115999999996, 126.538045]]

In [22]:
lines3_3 = []
lines3_3.append(df31[['latitude_x','longitude_x']].values[11].tolist())
lines3_3.append(df31[['latitude_y','longitude_y']].values[11].tolist())
lines3_3

[[33.486115999999996, 126.538045], [33.487633, 126.54041399999998]]

In [23]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines3_1, color='blue', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines3_2, color='red', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines3_3, color='purple',weight=10,
          tooltip = 'PolyLine').add_to(m)
m.save('재영4.html')

In [24]:
lines1_1 = []
for i in range(0,9):
    lines1_1.append(df11[['latitude_x','longitude_x']].values[i].tolist())
    lines1_1.append(df11[['latitude_y','longitude_y']].values[i].tolist())
lines1_1

[[33.460157, 126.44684299999999],
 [33.460544, 126.44760500000001],
 [33.460544, 126.44760500000001],
 [33.460634999999996, 126.447795],
 [33.460634999999996, 126.447795],
 [33.460782, 126.448079],
 [33.460782, 126.448079],
 [33.46309, 126.452479],
 [33.46309, 126.452479],
 [33.463342, 126.45410600000001],
 [33.463342, 126.45410600000001],
 [33.465863, 126.45638400000001],
 [33.465863, 126.45638400000001],
 [33.469456, 126.459953],
 [33.469456, 126.459953],
 [33.470483, 126.46084599999999],
 [33.470483, 126.46084599999999],
 [33.472819, 126.46303]]

In [25]:
lines1_2 = []
lines1_2.append(df11[['latitude_x','longitude_x']].values[9].tolist())
lines1_2.append(df11[['latitude_y','longitude_y']].values[9].tolist())
lines1_2

[[33.472819, 126.46303], [33.478257, 126.46808100000001]]

In [26]:
lines1_3 = []
for i in range(10,19):
    lines1_3.append(df11[['latitude_x','longitude_x']].values[i].tolist())
    lines1_3.append(df11[['latitude_y','longitude_y']].values[i].tolist())
lines1_3

[[33.478257, 126.46808100000001],
 [33.480678999999995, 126.47221599999999],
 [33.480678999999995, 126.47221599999999],
 [33.481156, 126.47283700000001],
 [33.481156, 126.47283700000001],
 [33.481901, 126.47375600000001],
 [33.481901, 126.47375600000001],
 [33.482819, 126.474875],
 [33.482819, 126.474875],
 [33.483418, 126.4756],
 [33.483418, 126.4756],
 [33.483963, 126.47625900000001],
 [33.483963, 126.47625900000001],
 [33.484642, 126.477124],
 [33.484642, 126.477124],
 [33.485054999999996, 126.47781],
 [33.485054999999996, 126.47781],
 [33.485278, 126.478223]]

In [27]:
lines1_4 = []
for i in range(19,23):
    lines1_4.append(df11[['latitude_x','longitude_x']].values[i].tolist())
    lines1_4.append(df11[['latitude_y','longitude_y']].values[i].tolist())
lines1_4

[[33.485278, 126.478223],
 [33.486, 126.47955],
 [33.486, 126.47955],
 [33.486327, 126.48015],
 [33.486327, 126.48015],
 [33.487088, 126.481498],
 [33.487088, 126.481498],
 [33.487756, 126.48251200000001]]

In [28]:
lines1_5 = []
for i in range(23,27):
    lines1_5.append(df11[['latitude_x','longitude_x']].values[i].tolist())
    lines1_5.append(df11[['latitude_y','longitude_y']].values[i].tolist())
lines1_5

[[33.487756, 126.48251200000001],
 [33.488395000000004, 126.483507],
 [33.488395000000004, 126.483507],
 [33.490078000000004, 126.486558],
 [33.490078000000004, 126.486558],
 [33.490805, 126.48786100000001],
 [33.490805, 126.48786100000001],
 [33.491513, 126.489081]]

In [29]:
lines1_6 = []
lines1_6.append(df11[['latitude_x','longitude_x']].values[27].tolist())
lines1_6.append(df11[['latitude_y','longitude_y']].values[27].tolist())
lines1_6

[[33.491513, 126.489081], [33.492335, 126.490247]]

In [30]:
lines1_7 = []
lines1_7.append(df11[['latitude_x','longitude_x']].values[28].tolist())
lines1_7.append(df11[['latitude_y','longitude_y']].values[28].tolist())
lines1_7

[[33.492335, 126.490247], [33.493793, 126.492189]]

In [31]:
center = [33.37835,126.54598]
m = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines1_1, color='red', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_2, color='orange', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_3, color='yellow', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_4, color='green', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_5, color='blue', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_6, color='black', weight=10,
          tooltip = 'PolyLine').add_to(m)
f.PolyLine(locations=lines1_7, color='purple', weight=10,
          tooltip = 'PolyLine').add_to(m)
m.save('무수천-신광.html')

In [32]:
m

In [33]:
lines2_1 = []
for i in range(0,7):
    lines2_1.append(df21[['latitude_x','longitude_x']].values[i].tolist())
    lines2_1.append(df21[['latitude_y','longitude_y']].values[i].tolist())
lines2_1

[[33.493624, 126.496769],
 [33.493565999999994, 126.497524],
 [33.493565999999994, 126.497524],
 [33.493458000000004, 126.500128],
 [33.493458000000004, 126.500128],
 [33.493031, 126.50818799999999],
 [33.493031, 126.50818799999999],
 [33.492841999999996, 126.511255],
 [33.492841999999996, 126.511255],
 [33.492567, 126.515227],
 [33.492567, 126.515227],
 [33.492444, 126.51687199999999],
 [33.492444, 126.51687199999999],
 [33.492272, 126.51971100000002]]

In [34]:
lines2_2 = []
for i in range(7,11):
    lines2_2.append(df21[['latitude_x','longitude_x']].values[i].tolist())
    lines2_2.append(df21[['latitude_y','longitude_y']].values[i].tolist())
lines2_2

[[33.492272, 126.51971100000002],
 [33.492222999999996, 126.521426],
 [33.492222999999996, 126.521426],
 [33.492139, 126.52825],
 [33.492139, 126.52825],
 [33.49309, 126.531131],
 [33.494763, 126.533654],
 [33.49553, 126.53478899999999]]

In [35]:
lines2_3 = []
for i in range(10,16):
    lines2_3.append(df21[['latitude_x','longitude_x']].values[i].tolist())
    lines2_3.append(df21[['latitude_y','longitude_y']].values[i].tolist())
lines2_3

[[33.494763, 126.533654],
 [33.49553, 126.53478899999999],
 [33.49553, 126.53478899999999],
 [33.496243, 126.535822],
 [33.496243, 126.535822],
 [33.496945000000004, 126.53688400000001],
 [33.496945000000004, 126.53688400000001],
 [33.497640999999994, 126.53796100000001],
 [33.497640999999994, 126.53796100000001],
 [33.498544, 126.539693],
 [33.498544, 126.539693],
 [33.499427000000004, 126.541298]]

In [36]:
lines2_4 = []
lines2_4.append(df21[['latitude_x','longitude_x']].values[16].tolist())
lines2_4.append(df21[['latitude_y','longitude_y']].values[16].tolist())
lines2_4

[[33.499427000000004, 126.541298], [33.500772, 126.54383700000001]]

In [37]:
lines2_5 = []
lines2_5.append(df21[['latitude_x','longitude_x']].values[17].tolist())
lines2_5.append(df21[['latitude_y','longitude_y']].values[17].tolist())
lines2_5

[[33.500772, 126.54383700000001], [33.502681, 126.54746200000001]]

In [38]:
lines2_6 = []
lines2_6.append(df21[['latitude_x','longitude_x']].values[18].tolist())
lines2_6.append(df21[['latitude_y','longitude_y']].values[18].tolist())
lines2_6

[[33.502681, 126.54746200000001], [33.504378, 126.550611]]

In [39]:
df21

,index,Link_ID,시점,latitude_x,longitude_x,종점,latitude_y,longitude_y,0,1,...,14,15,16,17,18,19,20,21,22,23
0,0,4050134300,마리나사거리,33.493624,126.496769,NaN,33.493566,126.497524,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4050133900,NaN,33.493566,126.497524,세기1차,33.493458,126.500128,4,2,...,8,9,2,5,5,4,5,4,2,2
2,2,4050132700,세기1차,33.493458,126.500128,연미마을,33.493031,126.508188,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4050132100,연미마을,33.493031,126.508188,사평마을,33.492842,126.511255,13534,9532,...,61796,63298,67384,68681,72372,51307,40101,32472,28231,19107
4,4,4050131400,사평마을,33.492842,126.511255,오라대교,33.492567,126.515227,0,0,...,0,0,0,0,0,0,0,0,0,0
5,5,4050130600,오라대교,33.492567,126.515227,오라1동,33.492444,126.516872,16177,11025,...,71761,70911,74707,78944,80950,56342,45024,38968,31967,22830
6,6,4050129300,오라1동,33.492444,126.516872,보건소사거리,33.492272,126.519711,14098,9850,...,62135,59562,60481,64490,65644,48362,38961,34032,26929,18452
7,7,4050128700,보건소사거리,33.492272,126.519711,도노교,33.492223,126.521426,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8,4050127600,도노교,33.492223,126.521426,제주지방합동청사삼거리,33.492139,126.528250,12980,8347,...,53306,50948,52246,53783,56008,42365,36703,32631,25289,17780
9,10,4050127700,도남사거리,33.492139,126.528250,-,33.493090,126.531131,0,0,...,0,0,0,0,0,0,0,0,0,0
10,12,4050136300,8호광장,33.494763,126.533654,-,33.495530,126.534789,0,0,...,0,0,0,0,0,0,0,0,0,0
11,13,4050139100,-,33.495530,126.534789,이도2동주민센터,33.496243,126.535822,0,0,...,0,0,0,0,0,0,0,0,0,0
12,14,4050142300,이도2동주민센터,33.496243,126.535822,-,33.496945,126.536884,0,0,...,0,0,0,0,0,0,0,0,0,0
13,15,4050144700,-,33.496945,126.536884,변전소사거리,33.497641,126.537961,14223,9759,...,52778,52372,54596,55295,59067,47923,38424,35326,28748,21009
14,16,4050147700,변전소사거리,33.497641,126.537961,NaN,33.498544,126.539693,0,0,...,0,0,0,0,0,0,0,0,0,0
15,17,4050150800,NaN,33.498544,126.539693,산지2교,33.499427,126.541298,0,0,...,0,0,0,0,0,0,0,0,0,0
16,18,4050152600,산지2교,33.499427,126.541298,제주은행사거리,33.500772,126.543837,12061,7875,...,48963,46373,45382,47391,47688,38213,30812,29060,22920,16444
17,19,4050156500,제주은행사거리,33.500772,126.543837,동광초교,33.502681,126.547462,11524,7494,...,42952,40186,41686,42589,43449,33208,27647,26740,21404,16221
18,20,4050160700,동광초교,33.502681,126.547462,우성아파트사거리,33.504378,126.550611,0,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
center = [33.37835,126.54598]
m2 = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines2_1, color='red', weight=10,
          tooltip = 'PolyLine').add_to(m2)
f.PolyLine(locations=lines2_2, color='orange', weight=10,
          tooltip = 'PolyLine').add_to(m2)
f.PolyLine(locations=lines2_3, color='yellow', weight=10,
          tooltip = 'PolyLine').add_to(m2)
f.PolyLine(locations=lines2_4, color='green', weight=10,
          tooltip = 'PolyLine').add_to(m2)
f.PolyLine(locations=lines2_5, color='blue', weight=10,
          tooltip = 'PolyLine').add_to(m2)
f.PolyLine(locations=lines2_6, color='black', weight=10,
          tooltip = 'PolyLine').add_to(m2)
m2.save('마리나-거로.html')

In [41]:
m2

In [42]:
lines3_1 = []
lines3_1.append(df31[['latitude_x','longitude_x']].values[0].tolist())
lines3_1.append(df31[['latitude_y','longitude_y']].values[0].tolist())
# lines3_1.append(df31[['latitude_x','longitude_x']].values[1].tolist())
# lines3_1.append(df31[['latitude_y','longitude_y']].values[1].tolist())
lines3_1

[[33.481796, 126.49486599999999], [33.481805, 126.49659399999999]]

In [43]:
lines3_2 = []
for i in range(1,10):
    lines3_2.append(df31[['latitude_x','longitude_x']].values[i].tolist())
    lines3_2.append(df31[['latitude_y','longitude_y']].values[i].tolist())
lines3_2

[[33.481805, 126.49659399999999],
 [33.481291, 126.508627],
 [33.481291, 126.508627],
 [33.481062, 126.515579],
 [33.481062, 126.515579],
 [33.481027000000005, 126.51661499999999],
 [33.481027000000005, 126.51661499999999],
 [33.480946, 126.51831999999999],
 [33.480946, 126.51831999999999],
 [33.480931, 126.51899099999999],
 [33.480931, 126.51899099999999],
 [33.480682, 126.525322],
 [33.480682, 126.525322],
 [33.481353999999996, 126.530093],
 [33.481353999999996, 126.530093],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999],
 [33.485485, 126.53708999999999]]

In [44]:
lines3_3 = []
lines3_3.append(df31[['latitude_x','longitude_x']].values[10].tolist())
lines3_3.append(df31[['latitude_y','longitude_y']].values[10].tolist())
lines3_3

[[33.485485, 126.53708999999999], [33.486115999999996, 126.538045]]

In [45]:
center = [33.37835,126.54598]
m3 = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines3_1, color='red', weight=10,
          tooltip = 'PolyLine').add_to(m3)
f.PolyLine(locations=lines3_2, color='orange', weight=10,
          tooltip = 'PolyLine').add_to(m3)
f.PolyLine(locations=lines3_3, color='yellow', weight=10,
          tooltip = 'PolyLine').add_to(m3)
m3.save('신시가지-중앙여고.html')

In [46]:
m3

In [47]:
lines4_1 = []
for i in range(0,4):
    lines4_1.append(df41[['latitude_x','longitude_x']].values[i].tolist())
    lines4_1.append(df41[['latitude_y','longitude_y']].values[i].tolist())
lines4_1

[[33.509468, 126.52349099999999],
 [33.507812, 126.52435],
 [33.507812, 126.52435],
 [33.505813, 126.525547],
 [33.505813, 126.525547],
 [33.504811, 126.52623999999999],
 [33.504811, 126.52623999999999],
 [33.50073, 126.52910700000001]]

In [48]:
lines4_2 = []
for i in range(4,10):
    lines4_2.append(df41[['latitude_x','longitude_x']].values[i].tolist())
    lines4_2.append(df41[['latitude_y','longitude_y']].values[i].tolist())
lines4_2

[[33.50073, 126.52910700000001],
 [33.499509, 126.52993000000001],
 [33.499509, 126.52993000000001],
 [33.497725, 126.53113300000001],
 [33.497725, 126.53113300000001],
 [33.497128000000004, 126.531604],
 [33.497128000000004, 126.531604],
 [33.496316, 126.532152],
 [33.496316, 126.532152],
 [33.495239, 126.533123],
 [33.495239, 126.533123],
 [33.494763, 126.533654]]

In [49]:
lines4_3 = []
for i in range(10,12):
    lines4_3.append(df41[['latitude_x','longitude_x']].values[i].tolist())
    lines4_3.append(df41[['latitude_y','longitude_y']].values[i].tolist())
lines4_3

[[33.494763, 126.533654],
 [33.492717999999996, 126.535597],
 [33.492717999999996, 126.535597],
 [33.491863, 126.536409]]

In [50]:
lines4_4 = []
for i in range(12,15):
    lines4_4.append(df41[['latitude_x','longitude_x']].values[i].tolist())
    lines4_4.append(df41[['latitude_y','longitude_y']].values[i].tolist())
lines4_4

[[33.491863, 126.536409],
 [33.490311, 126.53791000000001],
 [33.490311, 126.53791000000001],
 [33.489160999999996, 126.539],
 [33.489160999999996, 126.539],
 [33.487633, 126.54041399999998]]

In [51]:
lines4_5 = []
lines4_5.append(df41[['latitude_x','longitude_x']].values[15].tolist())
lines4_5.append(df41[['latitude_y','longitude_y']].values[15].tolist())
lines4_5

[[33.487633, 126.54041399999998], [33.485489, 126.54250400000001]]

In [52]:
lines4_6 = []
lines4_6.append(df41[['latitude_x','longitude_x']].values[16].tolist())
lines4_6.append(df41[['latitude_y','longitude_y']].values[16].tolist())
lines4_6

[[33.485489, 126.54250400000001], [33.48355, 126.54342]]

In [53]:
lines4_7 = []
lines4_7.append(df41[['latitude_x','longitude_x']].values[17].tolist())
lines4_7.append(df41[['latitude_y','longitude_y']].values[17].tolist())
lines4_7

[[33.48355, 126.54342], [33.478001, 126.543843]]

In [54]:
center = [33.37835,126.54598]
m4 = f.Map(location=center, zoom_start=10)
f.PolyLine(locations=lines4_1, color='red', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_2, color='orange', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_3, color='yellow', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_4, color='green', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_5, color='blue', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_6, color='black', weight=10,
          tooltip = 'PolyLine').add_to(m4)
f.PolyLine(locations=lines4_7, color='purple', weight=10,
          tooltip = 'PolyLine').add_to(m4)
m4.save('남문-아라초.html')

In [55]:
m4